version: '2'
services:
  app:
    image: 'demo_web:latest'
    build: .
    ports:
      - "8080:8080"
#    env_file: .env
    depends_on:
      - db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/crudCliente
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=root
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#    volumes:
#      - ./webapp:/opt/webapp
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=crudCliente
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
